//created on: 27 Sep, 2018
package com.bbdrools

//list any import classes here.

import com.bbdrools.model.Discount;
import com.bbdrools.model.Product;

//declare any global variables here

rule "Best SP"
    when
        $product : Product( $discounts:getDiscounts() && null != $discounts)
        $discount : Discount() from accumulate(($discount : Discount ($discountPrice : getDiscountPrice()) from $discounts), 
                                    min($discountPrice)) 
    then
        System.out.println("Best discount: "+ discount); 
end